window.__ModuleLoader__.load({id:'@fluxyard/harness-extensions',factory:require=>{
  const React=require('react'), {createPortal}=require('react-dom'), h=React.createElement
  const empty=()=>({title:'未命名演示稿',style:'minimal',enabled:false,slides:[{title:'第一页',bullets:[]}]})
  async function request(sessionId,action,extra={}) {
    const result=await fetch('/fluxyard/ppt',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({sessionId,action,...extra})})
    if(!result.ok) { let error;try{error=(await result.json()).error}catch{};throw new Error(error||'演示服务暂不可用，请稍后重试。') }
    return action==='export'?result.blob():result.json()
  }
  function Presentation({id}) {
    const dialogRef=React.useRef(null),entryRef=React.useRef(null)
    const [open,setOpen]=React.useState(false),[draft,setDraft]=React.useState(empty),[revision,setRevision]=React.useState(0),[busy,setBusy]=React.useState(false),[error,setError]=React.useState(''),[page,setPage]=React.useState(0),[ready,setReady]=React.useState(false),[outline,setOutline]=React.useState('第一页')
    React.useEffect(()=>{if(!open)return;let active=true;setBusy(true);setReady(false);setDraft(empty());setOutline('第一页');setError('');setPage(0);request(id,'read').then(value=>{if(active){const loaded=value?.draft||empty();setDraft(loaded);setOutline(loaded.slides.map(slide=>[slide.title,...slide.bullets].join('\n')).join('\n\n'));setRevision(value?.revision||0);setReady(true)}}).catch(e=>{if(active)setError(e.message)}).finally(()=>{if(active)setBusy(false)});return()=>{active=false}},[open,id])
    React.useEffect(()=>{if(!open||!ready)return;dialogRef.current?.querySelector('button')?.focus();return()=>entryRef.current?.focus()},[open,ready])
    function keyboard(event){if(event.key==='Escape'&&!busy){event.stopPropagation();setOpen(false)}if(event.key==='Tab'){const controls=[...dialogRef.current.querySelectorAll('button:not(:disabled),input:not(:disabled),select:not(:disabled),textarea:not(:disabled)')];const first=controls[0],last=controls[controls.length-1];if(event.shiftKey&&document.activeElement===first){event.preventDefault();last?.focus()}else if(!event.shiftKey&&document.activeElement===last){event.preventDefault();first?.focus()}}}
    const change=(key,value)=>setDraft(previous=>({...previous,[key]:value}))
    async function save(download) {setBusy(true);setError('');try{const saved=await request(id,'save',{draft,revision});setRevision(saved.revision);if(download){const blob=await request(id,'export',{revision:saved.revision});const url=URL.createObjectURL(blob),a=document.createElement('a');a.href=url;a.download='Fluxyard-presentation.pptx';a.click();setTimeout(()=>URL.revokeObjectURL(url),60000)}}catch(e){setError(e.message)}finally{setBusy(false)}}
    const current=draft.slides[page]||draft.slides[0]
    const button=(text,callback,disabled=false)=>h('button',{type:'button',onClick:callback,disabled},text)
    const field=(label,element)=>h('label',null,h('span',null,label),element)
    return h(React.Fragment,null,h('button',{type:'button',className:'fy-ppt-entry',ref:entryRef,onClick:()=>setOpen(true),title:'编辑当前会话的演示稿'},'PPT'),open?createPortal(h('div',{className:'fy-ppt-backdrop'},h('section',{className:'fy-ppt-dialog',ref:dialogRef,onKeyDown:keyboard,role:'dialog','aria-modal':true,'aria-label':'演示稿'},h('header',null,h('div',null,h('h2',null,'演示稿'),h('p',null,'手动编辑大纲，导出可编辑 PPTX')),button('关闭',()=>setOpen(false),busy)),error?h('p',{role:'alert',className:'fy-ppt-error'},error):null,busy?h('p',{role:'status'},'正在处理…'):null,h('div',{className:'fy-ppt-body'},h('div',{className:'fy-ppt-form'},field('演示标题',h('input',{value:draft.title,maxLength:160,disabled:!ready||busy,onChange:e=>change('title',e.target.value)})),field('样式',h('select',{value:draft.style,disabled:!ready||busy,onChange:e=>change('style',e.target.value)},[['minimal','简约'],['business','商务'],['course','讲义']].map(([value,label])=>h('option',{value,key:value},label)))),h('label',{className:'fy-ppt-mode'},h('input',{type:'checkbox',checked:draft.enabled,disabled:!ready||busy,onChange:e=>change('enabled',e.target.checked)}),h('span',null,'将已保存的大纲用于当前会话')),h('small',null,'保存后在下一次发送时生效，不会自动调用模型。'),field('每页大纲',h('textarea',{value:outline,disabled:!ready||busy,onChange:e=>{setOutline(e.target.value);const slides=e.target.value.split(/\n\s*\n/).map(block=>{const [title,...bullets]=block.split('\n');return{title,bullets:bullets.filter(Boolean)}});change('slides',slides);setPage(0)},rows:12})),h('small',null,'每段是一页，首行为标题，其余为要点；用空行分隔，最多 12 页。')),h('div',{className:'fy-ppt-preview'},h('div',{className:'fy-ppt-slide','data-style':draft.style},h('h3',null,current.title),h('ul',null,current.bullets.map((text,i)=>h('li',{key:i},text)))),h('nav',null,button('上一页',()=>setPage(page-1),page===0),h('span',null,`${page+1} / ${draft.slides.length}`),button('下一页',()=>setPage(page+1),page>=draft.slides.length-1)),h('small',null,'内容预览；实际 PPTX 排版可能不同。'))),h('footer',null,h('span',null,revision?'已保存版本 '+revision:'尚未保存'),button('保存大纲',()=>save(false),busy||!ready),button('导出 PPTX',()=>save(true),busy||!ready)))),document.body):null)
  }
  return {inject:['slots'],apply(ctx){
    ctx.effect(()=>{const style=document.createElement('style');style.textContent=`.fy-ppt-entry{border:1px solid #d4d4d8;background:transparent;border-radius:8px;padding:4px 9px;font:inherit;color:inherit;cursor:pointer}.fy-ppt-backdrop{position:fixed;inset:0;z-index:10000;background:#0005;display:grid;place-items:center;padding:24px}.fy-ppt-dialog{background:var(--background,#fff);color:var(--foreground,#18181b);border-radius:20px;padding:24px;width:min(100%,980px);max-height:90vh;overflow:auto;box-shadow:0 20px 80px #0003}.fy-ppt-dialog header,.fy-ppt-dialog footer{display:flex;align-items:center;gap:12px;justify-content:space-between}.fy-ppt-dialog h2{font-size:22px;margin:0}.fy-ppt-dialog p,.fy-ppt-dialog small{color:#71717a}.fy-ppt-dialog button{padding:8px 14px;border:1px solid #d4d4d8;border-radius:8px;cursor:pointer;background:transparent;color:inherit}.fy-ppt-dialog button:disabled{opacity:.4;cursor:default}.fy-ppt-body{display:grid;grid-template-columns:320px 1fr;gap:24px;margin:20px 0}.fy-ppt-form label{display:grid;gap:8px;margin-bottom:16px}.fy-ppt-form .fy-ppt-mode{display:flex;align-items:center;gap:8px;margin:12px 0}.fy-ppt-mode input{width:16px;height:16px}.fy-ppt-form input,.fy-ppt-form select,.fy-ppt-form textarea{border:1px solid #d4d4d8;padding:10px;border-radius:8px;background:transparent;color:inherit;font:inherit;resize:vertical}.fy-ppt-slide{aspect-ratio:16/9;background:white;color:#334155;border-left:6px solid #334155;padding:24px;overflow:auto}.fy-ppt-slide[data-style=business]{border-color:#2563eb}.fy-ppt-slide[data-style=course]{border-color:#15803d}.fy-ppt-slide h3{font-size:24px;margin:0 0 20px}.fy-ppt-slide li{margin:10px 0}.fy-ppt-preview nav{display:flex;justify-content:space-between;align-items:center;margin:16px 0}.fy-ppt-error{color:#b91c1c!important}.fy-ppt-dialog footer>span{margin-right:auto}@media(max-width:800px){.fy-ppt-body{grid-template-columns:1fr}}`;document.head.append(style);return()=>style.remove()})
    ctx.slots.inject('conversation.input.left',()=>ctx.slots.register({name:'conversation.input.left',id:'fluxyard-ppt',order:10,inject:sessionId=>({id:sessionId})},Presentation))
  }}
}})
